framework:
  serializer:
    enabled: true
    name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    default_context:
      enable_max_depth: true
      groups: ['note:read', 'note:write']